version: '3'

services:

  db:
    logging:
      driver: none
    image: mongo:4.4.6 # 4.4.6 supports non-avx
    ports:
      - "27017:27017"
    volumes:
      - fi_data:/data/db

  server:
    image: matthewnitschke/fi-server:latest
    ports:
      - "8080:8080"
    environment:
      NODE_ENV: production
      SESSION_SECRET: ${SESSION_SECRET}
      PLAID_CLIENT_ID: ${PLAID_CLIENT_ID}
      PLAID_SECRET: ${PLAID_SECRET}
  
  client:
    image: matthewnitschke/fi:latest
    ports:
      - "80:80"

volumes:
  fi_data:
