services:
  # ngrok:
  #   entrypoint: ["echo", "ngrok disabled in dev mode"]

  server:
    build:
      context: .
      dockerfile: Dockerfile-dev
    volumes:
      - ./:/app
    environment:
      - NODE_ENV=development
      - SESSION_SECRET="Shhh... development only"
