services:

  server:
    build:
      context: .
      dockerfile: Dockerfile-dev
    volumes:
      - ./:/app
    environment:
      - NODE_ENV=development
      - SESSION_SECRET="Shhh... development only"
  
  client:
    entrypoint: ["echo", "client disabled in dev mode, npm run start in fi repo"]
